//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the constrained_ik package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __constrained_ik__CLIKDYNAMICCONFIG_H__
#define __constrained_ik__CLIKDYNAMICCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace constrained_ik
{
  class CLIKDynamicConfigStatics;

  class CLIKDynamicConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(CLIKDynamicConfig &config, const CLIKDynamicConfig &max, const CLIKDynamicConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CLIKDynamicConfig &config1, const CLIKDynamicConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CLIKDynamicConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CLIKDynamicConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CLIKDynamicConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CLIKDynamicConfig &config) const = 0;
      virtual void getValue(const CLIKDynamicConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T CLIKDynamicConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (CLIKDynamicConfig::* field);

      virtual void clamp(CLIKDynamicConfig &config, const CLIKDynamicConfig &max, const CLIKDynamicConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CLIKDynamicConfig &config1, const CLIKDynamicConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CLIKDynamicConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CLIKDynamicConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CLIKDynamicConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CLIKDynamicConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CLIKDynamicConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CLIKDynamicConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CLIKDynamicConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<CLIKDynamicConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CLIKDynamicConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("debug_mode"==(*_i)->name){debug_mode = boost::any_cast<bool>(val);}
        if("allow_joint_convergence"==(*_i)->name){allow_joint_convergence = boost::any_cast<bool>(val);}
        if("allow_primary_normalization"==(*_i)->name){allow_primary_normalization = boost::any_cast<bool>(val);}
        if("allow_auxiliary_nomalization"==(*_i)->name){allow_auxiliary_nomalization = boost::any_cast<bool>(val);}
        if("limit_primary_motion"==(*_i)->name){limit_primary_motion = boost::any_cast<bool>(val);}
        if("limit_auxiliary_motion"==(*_i)->name){limit_auxiliary_motion = boost::any_cast<bool>(val);}
        if("limit_auxiliary_interations"==(*_i)->name){limit_auxiliary_interations = boost::any_cast<bool>(val);}
        if("solver_max_iterations"==(*_i)->name){solver_max_iterations = boost::any_cast<int>(val);}
        if("solver_min_iterations"==(*_i)->name){solver_min_iterations = boost::any_cast<int>(val);}
        if("primary_max_motion"==(*_i)->name){primary_max_motion = boost::any_cast<double>(val);}
        if("auxiliary_max_iterations"==(*_i)->name){auxiliary_max_iterations = boost::any_cast<int>(val);}
        if("auxiliary_max_motion"==(*_i)->name){auxiliary_max_motion = boost::any_cast<double>(val);}
        if("primary_norm"==(*_i)->name){primary_norm = boost::any_cast<double>(val);}
        if("auxiliary_norm"==(*_i)->name){auxiliary_norm = boost::any_cast<double>(val);}
        if("primary_gain"==(*_i)->name){primary_gain = boost::any_cast<double>(val);}
        if("auxiliary_gain"==(*_i)->name){auxiliary_gain = boost::any_cast<double>(val);}
        if("joint_convergence_tol"==(*_i)->name){joint_convergence_tol = boost::any_cast<double>(val);}
      }
    }

    bool debug_mode;
bool allow_joint_convergence;
bool allow_primary_normalization;
bool allow_auxiliary_nomalization;
bool limit_primary_motion;
bool limit_auxiliary_motion;
bool limit_auxiliary_interations;
int solver_max_iterations;
int solver_min_iterations;
double primary_max_motion;
int auxiliary_max_iterations;
double auxiliary_max_motion;
double primary_norm;
double auxiliary_norm;
double primary_gain;
double auxiliary_gain;
double joint_convergence_tol;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool debug_mode;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool allow_joint_convergence;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool allow_primary_normalization;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool allow_auxiliary_nomalization;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool limit_primary_motion;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool limit_auxiliary_motion;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool limit_auxiliary_interations;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int solver_max_iterations;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int solver_min_iterations;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double primary_max_motion;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int auxiliary_max_iterations;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double auxiliary_max_motion;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double primary_norm;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double auxiliary_norm;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double primary_gain;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double auxiliary_gain;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double joint_convergence_tol;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CLIKDynamicConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CLIKDynamicConfig &__max__ = __getMax__();
      const CLIKDynamicConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CLIKDynamicConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CLIKDynamicConfig &__getDefault__();
    static const CLIKDynamicConfig &__getMax__();
    static const CLIKDynamicConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const CLIKDynamicConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void CLIKDynamicConfig::ParamDescription<std::string>::clamp(CLIKDynamicConfig &config, const CLIKDynamicConfig &max, const CLIKDynamicConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CLIKDynamicConfigStatics
  {
    friend class CLIKDynamicConfig;

    CLIKDynamicConfigStatics()
    {
CLIKDynamicConfig::GroupDescription<CLIKDynamicConfig::DEFAULT, CLIKDynamicConfig> Default("Default", "", 0, 0, true, &CLIKDynamicConfig::groups);
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.debug_mode = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.debug_mode = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.debug_mode = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("debug_mode", "bool", 0, "Set the solver in a debug state.", "", &CLIKDynamicConfig::debug_mode)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("debug_mode", "bool", 0, "Set the solver in a debug state.", "", &CLIKDynamicConfig::debug_mode)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.allow_joint_convergence = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.allow_joint_convergence = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.allow_joint_convergence = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("allow_joint_convergence", "bool", 0, "Allow the solver to converge based on joint convergence.", "", &CLIKDynamicConfig::allow_joint_convergence)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("allow_joint_convergence", "bool", 0, "Allow the solver to converge based on joint convergence.", "", &CLIKDynamicConfig::allow_joint_convergence)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.allow_primary_normalization = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.allow_primary_normalization = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.allow_primary_normalization = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("allow_primary_normalization", "bool", 0, "Allow the solver to normalize primary motion.", "", &CLIKDynamicConfig::allow_primary_normalization)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("allow_primary_normalization", "bool", 0, "Allow the solver to normalize primary motion.", "", &CLIKDynamicConfig::allow_primary_normalization)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.allow_auxiliary_nomalization = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.allow_auxiliary_nomalization = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.allow_auxiliary_nomalization = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("allow_auxiliary_nomalization", "bool", 0, "Allow the solver to normalize auxiliary motion", "", &CLIKDynamicConfig::allow_auxiliary_nomalization)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("allow_auxiliary_nomalization", "bool", 0, "Allow the solver to normalize auxiliary motion", "", &CLIKDynamicConfig::allow_auxiliary_nomalization)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.limit_primary_motion = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.limit_primary_motion = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.limit_primary_motion = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("limit_primary_motion", "bool", 0, "Allow the solver to limit the primary motion.", "", &CLIKDynamicConfig::limit_primary_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("limit_primary_motion", "bool", 0, "Allow the solver to limit the primary motion.", "", &CLIKDynamicConfig::limit_primary_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.limit_auxiliary_motion = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.limit_auxiliary_motion = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.limit_auxiliary_motion = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("limit_auxiliary_motion", "bool", 0, "Allow the solver to limit the auxiliary motion.", "", &CLIKDynamicConfig::limit_auxiliary_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("limit_auxiliary_motion", "bool", 0, "Allow the solver to limit the auxiliary motion.", "", &CLIKDynamicConfig::limit_auxiliary_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.limit_auxiliary_interations = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.limit_auxiliary_interations = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.limit_auxiliary_interations = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("limit_auxiliary_interations", "bool", 0, "Allow the solver to limit the number of auxiliary interation.", "", &CLIKDynamicConfig::limit_auxiliary_interations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<bool>("limit_auxiliary_interations", "bool", 0, "Allow the solver to limit the number of auxiliary interation.", "", &CLIKDynamicConfig::limit_auxiliary_interations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.solver_max_iterations = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.solver_max_iterations = 2147483647;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.solver_max_iterations = 500;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<int>("solver_max_iterations", "int", 0, "Solver's maximum number of iterations allowed.", "", &CLIKDynamicConfig::solver_max_iterations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<int>("solver_max_iterations", "int", 0, "Solver's maximum number of iterations allowed.", "", &CLIKDynamicConfig::solver_max_iterations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.solver_min_iterations = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.solver_min_iterations = 2147483647;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.solver_min_iterations = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<int>("solver_min_iterations", "int", 0, "Solver's minimum number of iterations required.", "", &CLIKDynamicConfig::solver_min_iterations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<int>("solver_min_iterations", "int", 0, "Solver's minimum number of iterations required.", "", &CLIKDynamicConfig::solver_min_iterations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.primary_max_motion = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.primary_max_motion = std::numeric_limits<double>::infinity();
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.primary_max_motion = 2.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("primary_max_motion", "double", 0, "Primary's maximum motion allowed.", "", &CLIKDynamicConfig::primary_max_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("primary_max_motion", "double", 0, "Primary's maximum motion allowed.", "", &CLIKDynamicConfig::primary_max_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auxiliary_max_iterations = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auxiliary_max_iterations = 2147483647;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auxiliary_max_iterations = 5;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<int>("auxiliary_max_iterations", "int", 0, "Auxiliary's maximum number of iteration allowed.", "", &CLIKDynamicConfig::auxiliary_max_iterations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<int>("auxiliary_max_iterations", "int", 0, "Auxiliary's maximum number of iteration allowed.", "", &CLIKDynamicConfig::auxiliary_max_iterations)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auxiliary_max_motion = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auxiliary_max_motion = std::numeric_limits<double>::infinity();
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auxiliary_max_motion = 0.2;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("auxiliary_max_motion", "double", 0, "Auxiliary's maximum motion allowed.", "", &CLIKDynamicConfig::auxiliary_max_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("auxiliary_max_motion", "double", 0, "Auxiliary's maximum motion allowed.", "", &CLIKDynamicConfig::auxiliary_max_motion)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.primary_norm = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.primary_norm = std::numeric_limits<double>::infinity();
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.primary_norm = 1.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("primary_norm", "double", 0, "Normalize primary motion to set value.", "", &CLIKDynamicConfig::primary_norm)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("primary_norm", "double", 0, "Normalize primary motion to set value.", "", &CLIKDynamicConfig::primary_norm)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auxiliary_norm = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auxiliary_norm = std::numeric_limits<double>::infinity();
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auxiliary_norm = 0.2;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("auxiliary_norm", "double", 0, "Normalize auxiliary motion to set value.", "", &CLIKDynamicConfig::auxiliary_norm)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("auxiliary_norm", "double", 0, "Normalize auxiliary motion to set value.", "", &CLIKDynamicConfig::auxiliary_norm)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.primary_gain = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.primary_gain = 1.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.primary_gain = 1.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("primary_gain", "double", 0, "Solver's primary motion update gain.", "", &CLIKDynamicConfig::primary_gain)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("primary_gain", "double", 0, "Solver's primary motion update gain.", "", &CLIKDynamicConfig::primary_gain)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auxiliary_gain = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auxiliary_gain = 1.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auxiliary_gain = 1.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("auxiliary_gain", "double", 0, "Solver's auxiliary motion update gain.", "", &CLIKDynamicConfig::auxiliary_gain)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("auxiliary_gain", "double", 0, "Solver's auxiliary motion update gain.", "", &CLIKDynamicConfig::auxiliary_gain)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.joint_convergence_tol = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.joint_convergence_tol = std::numeric_limits<double>::infinity();
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.joint_convergence_tol = 0.0001;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("joint_convergence_tol", "double", 0, "Solver's joint convergence tolerance.", "", &CLIKDynamicConfig::joint_convergence_tol)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CLIKDynamicConfig::AbstractParamDescriptionConstPtr(new CLIKDynamicConfig::ParamDescription<double>("joint_convergence_tol", "double", 0, "Solver's joint convergence tolerance.", "", &CLIKDynamicConfig::joint_convergence_tol)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CLIKDynamicConfig::AbstractGroupDescriptionConstPtr(new CLIKDynamicConfig::GroupDescription<CLIKDynamicConfig::DEFAULT, CLIKDynamicConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CLIKDynamicConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<CLIKDynamicConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CLIKDynamicConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CLIKDynamicConfig __max__;
    CLIKDynamicConfig __min__;
    CLIKDynamicConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CLIKDynamicConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CLIKDynamicConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CLIKDynamicConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const CLIKDynamicConfig &CLIKDynamicConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const CLIKDynamicConfig &CLIKDynamicConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const CLIKDynamicConfig &CLIKDynamicConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<CLIKDynamicConfig::AbstractParamDescriptionConstPtr> &CLIKDynamicConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CLIKDynamicConfig::AbstractGroupDescriptionConstPtr> &CLIKDynamicConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CLIKDynamicConfigStatics *CLIKDynamicConfig::__get_statics__()
  {
    const static CLIKDynamicConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CLIKDynamicConfigStatics::get_instance();

    return statics;
  }


}

#endif // __CLIKDYNAMICRECONFIGURATOR_H__
